"""Short links for The Little Book of Semaphores: greenteapress.com/sem2/N.

links.csv is the catalog. Numbers are permanent: never reuse or renumber; to fix
a dead link, change its target. book.tex prints them with \\shortlink{N}.

usage:
  python shortlinks.py check                 # every \\shortlink{N} in book.tex is in links.csv, and vice versa
  python shortlinks.py htaccess [PATH]       # write the redirects (default: ~/GreenTeaPress/greenteapress/sem2/.htaccess)

Then deploy from ~/GreenTeaPress: commit, and scripts/deploy_gtp.sh sem2
"""
import csv, os, re, sys

CODE = 'sem2'
HOME = 'https://greenteapress.com/wp/semaphores/'
HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT = os.path.expanduser(f'~/GreenTeaPress/greenteapress/{CODE}/.htaccess')


def load():
    with open(os.path.join(HERE, 'links.csv'), newline='') as f:
        rows = [(int(r['n']), r['target'], r['note']) for r in csv.DictReader(f)]
    ns = [n for n, _, _ in rows]
    assert ns == sorted(set(ns)), 'link numbers must be unique and in order'
    return rows


def check():
    rows = load()
    tex = open(os.path.join(HERE, 'book.tex'), encoding='latin-1').read()
    used = {int(n) for n in re.findall(r'\\shortlink\{(\d+)\}', tex)}
    known = {n for n, _, _ in rows}
    ok = True
    for n in sorted(used - known):
        print(f'book.tex uses \\shortlink{{{n}}}, which is not in links.csv'); ok = False
    for n in sorted(known - used):
        print(f'links.csv has {n}, which book.tex does not use (fine if retired)')
    print(f'{len(used)} short links used, {len(known)} in catalog')
    return ok


def htaccess(path=DEFAULT):
    rows = load()
    lines = [f'# Short links for The Little Book of Semaphores, 2nd edition: greenteapress.com/{CODE}/N',
             '# Generated by LittleBookOfSemaphores/book/shortlinks.py from book/links.csv. Do not edit here.',
             f'RedirectMatch 302 ^/{CODE}/?$ {HOME}']
    for n, target, note in rows:
        lines.append(f'# {note}')
        lines.append(f'RedirectMatch 302 ^/{CODE}/{n}/?$ {target}')
    lines.append('# Unknown numbers go to the book page')
    lines.append(f'RedirectMatch 302 ^/{CODE}/.+$ {HOME}')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'wrote {path}')


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'check'
    if cmd == 'check':
        sys.exit(0 if check() else 1)
    elif cmd == 'htaccess':
        htaccess(*sys.argv[2:3])
    else:
        sys.exit(__doc__)
